### ISSUE TITLE
Have a look at foghorn code

### ISSUE THREAD

**Issue by maelle** [lockedata/cransays#10]
In particular maybe `foghorn::cran_incoming()` can help make the code here more elegant? h/t @fmichonneau

**Comment by maelle** [comment]
@mitchelloharawild  since you're planning a PR you might want to look if there are ideas to borrow in  https://github.com/fmichonneau/foghorn/blob/master/R/cran_queue.R 😸

**Comment by maelle** [comment]
And in any case I'll need to add a section related work to the README.

**Comment by mitchelloharawild** [comment]
The foghorn code is neat, and seems to also parse the text using `read.table`. The ideas are fairly similar, slight difference is that I've used the url capabilities of the read.*() methods and foghorn uses curl to obtain the strings.

The cransays code also traverses the cran folders more dynamically (although afaik the ftp folder structure rarely changes).

**Comment by maelle** [comment]
There's now a related work subsection https://github.com/lockedata/cransays#related-work

Thanks @mitchelloharawild for looking at the code!
