### ISSUE TITLE
ORCID IDs

### ISSUE THREAD

**Issue by maelle** [lockedata/cransays#14]
@Bisaloo @mitchelloharawild do you want me to add your ORCID ID in the DESCRIPTION? 

More info: https://ropensci.org/technotes/2018/10/08/orcid/

**Comment by Bisaloo** [comment]
Sure, why not? My ID is `0000-0002-4094-1476`. I feel bad now because I did almost nothing but I like this idea of this page and I will look to how I can contribute in the future ^^.

**Comment by maelle** [comment]
don't feel bad, it was an useful contribution!

**Comment by mitchelloharawild** [comment]
I don't have an ORCID ID at this stage, but I will let you know if I set one up in the future.

**Comment by maelle** [comment]
Fine, I'll close this for now but do not hesitate to PR your ID.
