### ISSUE TITLE
Fix the timezone problem

### ISSUE THREAD

**Issue by maelle** [lockedata/cransays#15]
Currently there can be a negative time since submission which doesn't seem right.

**Comment by maelle** [comment]
![image](https://user-images.githubusercontent.com/8360597/46676914-d23b9380-cbe1-11e8-974c-3af17e9a33d5.png)

**Comment by maelle** [comment]
I wonder how we could guess the timezone of the times returned by CRAN.

**Comment by maelle** [comment]
I mean whether the info is in the page. Otherwise it'll really be guessing from info from our submissions.

**Comment by maelle** [comment]
Thanks to Jeroen "The server is in Austria: https://tools.keycdn.com/geo?host=cran.r-project.org "

**Comment by Bisaloo** [comment]
Ah, that's strange. Yesterday, I could see the timezone (UTC+2) right on the ftp page. I was wondering why this was an issue. But today, on a different computer, I can't see it anymore. But this means that this info is probably somehow stored on the server. It would be probably more robust to use this than the current server location. I will try to have a look tonight if I get some time.

**Comment by maelle** [comment]
> Yesterday, I could see the timezone (UTC+2) right on the ftp page. I was wondering why this was an issue.

Ahahah I can imagine you were surprised! Although I could have missed something obvious as well!

Very cool if you can have a look, I didn't have much luck when googling "find timezone of an FTP server", so I'd be fine with our assuming is Austria (the remaining issue are just ensuring time changes in winter/summer don't mess things up).

**Comment by Bisaloo** [comment]
yeah, I saw that :confused:. I am starting to wonder if Firefox is not simply displaying my own timezone :sweat_smile:. I'm trying to get my hands on a proxy with a different timezone to test this.

**Comment by stephlocke** [comment]
I've been using chrome and I've never seen a bit about the timezone

**Comment by Bisaloo** [comment]
Here is how it looks like in recent Firefox versions. But when I browse the page source, I can't see anything about the timezone. So it may simply be a UI thing...

![screenshot from 2018-10-10 17-38-22](https://user-images.githubusercontent.com/10783929/46748268-78a39980-ccb3-11e8-9d67-79e3e1733a39.png)

**Comment by Bisaloo** [comment]
By the way, if I understand correct, the `TIME` file in that folder could be used to find the server timezone (by comparing its content to its modification date).

```r
as.POSIXct(as.numeric(readLines("ftp://cran.r-project.org/pub/R/TIME")), origin = "1970-01-01")
```

Or we could just go with Vienna timezone, as @maelle suggested :laughing: I'm mainly concerned by daylight savings time.
