### ISSUE TITLE
Add an explanation for the different folders

### ISSUE THREAD

**Issue by Bisaloo** [lockedata/cransays#20]
Right now, it is a bit obscure for anyone unfamiliar with the submission process what each folder means. If I'm a package maintainer, I can see that my package has moved to `pretest` but what does it mean?

My understanding is that there is no official documentation about the meaning of each folder (it may even depends on each maintainer????) so this may be a bit difficult.

The diagram from https://github.com/edgararuiz/cran-stages could help here but I'm not sure under which license it's been released.

![](https://github.com/edgararuiz/cran-stages/raw/master/images/cran-diagram.png)

**Comment by maelle** [comment]
Maybe we can simply add a link to that GitHub repo, above the dashboard?

**Comment by Bisaloo** [comment]
I don't think it would help that much. I don't have data to support this but I think few people click on links.

Let's imagine you're a new R user, you find the dashboard by randomly clicking on a twitter link. First thing most people do is just scrolling and quickly skimming through the page to try and understand what it's about. If it doesn't catch my interest, I will simply close the tab without any further thought, without taking the time to read any of the text. I like pictures because it immediately catch your attention: "how, there it is! A guide on how to read this table."

**Comment by Bisaloo** [comment]
https://journal.r-project.org/archive/2018-1/cran.pdf

Here is a highly relevant article from R journal that details the submission pipeline and the function of each folder!

**Comment by maelle** [comment]
oh very cool, nice find! If you want, you can digest it into a small blurb for the dashboard page. 😉

**Comment by Bisaloo** [comment]
I'll give it a go in a couple of days, unless someone wants to do it first.

**Comment by maelle** [comment]
Ok! Enough contributions to make you "aut" 😜

**Comment by Bisaloo** [comment]
I haven't moved on this because I can't decide what to do. I still think a figure is clearer but:

1. https://journal.r-project.org/archive/2018-1/cran.pdf is an official source, which is always better
2. https://github.com/edgararuiz/cran-stages fig misses some info, such as "what is `pending`?"

What do you think I should do?

**Comment by stephlocke** [comment]
Add them all :)

**Comment by maelle** [comment]
@Bisaloo Any update? No rush of course, just curious. 😸

**Comment by Bisaloo** [comment]
No, sorry. I'll try to take care of this by the end of the week. Feel free to ping me if I end up forgetting again :wink:

**Comment by maelle** [comment]
When you do, don't forget to upgrade yourself from "ctb" to "aut". Thanks!
