### ISSUE TITLE
How to update information about folder meaning?

### ISSUE THREAD

**Issue by maelle** [lockedata/cransays#23]
There are now two new folders, "newbies" and "waiting".

Cc @Bisaloo

**Comment by Bisaloo** [comment]
Good catch! That's interesting. 

I had a look at some packages on `newbies` and none of them were on CRAN yet. So maybe that's a folder for first releases.

I'll keep an eye out on the next R journal issue in case there is some announcement about this.

**Comment by maelle** [comment]
Thanks!

It's a bit sad that we need to run after info like this :crying_cat_face:

**Comment by rstub** [comment]
From todays message on R-pkg-devel by Uwe:

> pending means a team member has to do a closer inspection and needs more time while waiting means user reactions, this is a recent change since we wrote the publication you cited.

**Comment by Bisaloo** [comment]
https://journal.r-project.org/archive/2019-1/cran.pdf

> New categories in the table above are newbies (a specific queue for the manual inspection of first time CRAN submissions) and waiting (packages for which the CRAN team waits for an answer from the maintainer).

:tada:
