### ISSUE TITLE
Website and dashboard not reachable

### ISSUE THREAD

**Issue by cderv** [lockedata/cransays#27]
I can't go on the dashboard
https://cransays.itsalocke.com/articles/dashboard.html
nor the website
https://cransays.itsalocke.com

Is this just me ?

**Comment by maelle** [comment]
No indeed you are not alone, it is now at lockedata.github.io/cransays and @stephlocke will soon add redirects.

**Comment by cderv** [comment]
Thanks! It was just bad timing then 😉 

I let you close now... or later when links from the README will be working again.

**Comment by stephlocke** [comment]
Ah yeah, I'd encountered some difficulty because I can't redirect a cname to a url with a directory. I think I need to basically make an empty netlify site that just has a redirect.

**Comment by maelle** [comment]
@stephlocke https://itsalocke.com/cransays/articles/dashboard.html is up but has old data whereas https://lockedata.github.io/cransays/articles/dashboard.html is up-to-date.

**Comment by pat-s** [comment]
The README link is not yet redirected :)

**Comment by maelle** [comment]
@stephlocke ping about https://github.com/lockedata/cransays/issues/27#issuecomment-571043364 :-)

**Comment by stephlocke** [comment]
I think I've solved the redirects now 👍
