### ISSUE TITLE
Dashboard is out of date

### ISSUE THREAD

**Issue by jonocarroll** [lockedata/cransays#28]
Appears to be last updated 2019-12-13 14:46 UTC+0000.

Brilliant site, by the way, looks great and very insightful for submitters. Cheers!!!

**Comment by maelle** [comment]
related to #27; https://lockedata.github.io/cransays/articles/dashboard.html is up-to-date. cc @stephlocke

**Comment by jonocarroll** [comment]
Ah, fantastic. Thank you.
