### ISSUE TITLE
Dashboard hasn't updated in a few days

### ISSUE THREAD

**Issue by ddsjoberg** [lockedata/cransays#38]
Thank you for creating this wonderful service!

I wanted to let you know that the dashboard hasn't updated in 3 days (in case you weren't already aware)
![image](https://user-images.githubusercontent.com/26774684/118732248-f5059e00-b807-11eb-8c11-02c2939d68b6.png)

🌴 🌞

**Comment by llrs** [comment]
Probably @maelle needs to renew the actions because if there hasn't been any commit in 3 months GitHub stops running the automatic schedule.

**Comment by maelle** [comment]
Yes, I've now re-launched it and I've set a calendar reminder at last. Thanks both!!
