### ISSUE TITLE
Stop hardcoding year

### ISSUE THREAD

**Issue by maelle** [lockedata/cransays#4]
whilst finding a way to guess the year probably from the difference between the current time and the submission time, taking timezones into account.

cf https://github.com/lockedata/cransays/blob/master/R/take-snapshot.R#L99

**Comment by mitchelloharawild** [comment]
The year will replace the time information in the ftp summary when required. For example:

```r
2 drwxr-sr-x    3 1021     1001         4096 May 10 14:38 done-delete                          DS        2018-10-09 22:30:02
3 drwxr-sr-x    2 1021     1001         4096 May 03  2017 notok                                DS        2018-10-09 22:30:02
```

**Comment by maelle** [comment]
I don't understand?

**Comment by maelle** [comment]
There hasn't been any taker yet @mitchelloharawild . Just sayin' 👼
