### ISSUE TITLE
Improve the sorting by time since submission

### ISSUE THREAD

**Issue by maelle** [lockedata/cransays#5]
Right now the sorting follows the character order, ideally it'd be sorted by number of days while keeping the current "pretty" display "number of days days ago"

**Comment by maelle** [comment]
or maybe have the unit at the top only

**Comment by jimhester** [comment]
Just came here to report this glad to see it fixed!

**Comment by maelle** [comment]
do you see it fixed? I think it's not deployed yet, am about to test it locally

**Comment by jimhester** [comment]
no it is not yet fixed on the site

**Comment by maelle** [comment]
I think I know what was wrong
