### ISSUE TITLE
Do we want to track changes to package locations etc?

### ISSUE THREAD

**Issue by stephlocke** [lockedata/cransays#8]
Why: For Science!
How: Google Big Query or something as part of the build
Pros: Insight into CRAN
Cons: Could be judgey

**Comment by maelle** [comment]
Technically, the build on Travis would update a Google Big Query database and the `take_snapshot` function would access that or would the Big Query data be for the archiving only? In any case by build it'd be cool to not query CRAN twice (once for the database and once for the dashboard). 🤔

**Comment by stephlocke** [comment]
big query for archiving only, tho it could also be an alright source if we wanted to read the dashboard from it

**Comment by maelle** [comment]
@stephlocke why big query btw?

**Comment by stephlocke** [comment]
seemed like a cheap storage util for this sort of simple accumulating data, plus it has some native ML capabilities built in so we would get to play 😉

**Comment by maelle** [comment]
So we need to run a code every hour to create the snapshot (with a bit more info cf #9 ) and send it to a Big Query project. Probaby with `bigrquery` + `DBI`.

**Comment by maelle** [comment]
The data is in the commit history of gh-pages at the moment, I suppose.

**Comment by stephlocke** [comment]
If the dashboard.Rmd could append the data to a csv as the start of our data capture mechanism, that'd be good.

**Comment by maelle** [comment]
So two tasks here

* Use GH commits to retrieve past data

* Add the appending of a csv to the data capture.

**Comment by stephlocke** [comment]
I'd focus on the append first. The looking through git versions of a html file (I believe we gotta look at the compiled html file?) sounds a lot harder and it'd be better to get fresh data capturing sooner. Backfilling is a nice to have!

**Comment by maelle** [comment]
Bad workflow at the moment. https://github.com/lockedata/cransays/blob/master/.github/workflows/master.yml branch https://github.com/lockedata/cransays/tree/history

* how to I create an orphan branch and then add CSV files to it w/o adding the rest? @stephlocke 

* add the actual submission time to the csv.

once the workflow is improved, add it to cron.yml

**Comment by hadley** [comment]
I think this was done in aa0ab6b
